name: Calculo Diario de Mercados

on:
  schedule:
    - cron: "0 6 * * *"   # Todos los días a las 06:00 UTC
  workflow_dispatch:        # Para lanzarlo manualmente

permissions:
  contents: write           # IMPORTANTE: permite hacer commit desde GitHub Actions

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        run: python calcular_mercado.py

      - name: Hacer commit de los cambios
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add resultados.json
          git commit -m "Actualización diaria de resultados" || echo "No hay cambios"
          git push
